export enum SkillName {
  LISTENING = "LISTENING",
  READING = "READING",
  WRITING = "WRITING",
  SPEAKING = "SPEAKING",
  BONUS = "BONUS",
  MIDTERMSUM = "MIDTERMSUM",
  FINALSUM = "FINALSUM",
  MIDTERMPER = "MIDTERMPER",
  FINALPER = "FINALPER",
}